[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "support_vector_machines"
version = "0.0.1"
dependencies = [
    "scikit-learn",
    "matplotlib",
    "pandas"
]

[tool.setuptools.packages.find]
include = ["support_vector_machines"]

